# 配置文件说明 https://github.com/hect0x7/JMComic-Crawler-Python/blob/master/assets/docs/sources/option_file_syntax.md
download:
  image:
    suffix: .png

dir_rule:
  base_dir: books
  rule: 'Bd_Aid_Pindex'
client:
  postman:
    meta_data:
      proxies: system